language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
env:
  global:
    - secure: jKjofiDPJNCB28wmsSxc8wXHzeyPOPZky2g2PffedVpFWokY6WbCQizGH4D/O1mKBTg6SAT0Yjh1ijeEd3kHbh6v84NKC9WGjompBzyKtPOEtV3gDo8dkPguuV/bwNWz2KR9KP1FybiaXIsXsK5asCc6IFZZQApuQs0fyC3CGdY=
    - secure: RPJpJdQn/hIZETNcquYlf2mzetvPR1/g4OBJIQdN5BbSFb7t+trhlEu/tkOVLHxcw4unIuVqU8QIQvpmwt8Q+4JChlxcObCr/J61lZHLTmfauXWXwBBjS1+6FIJSpJITMFK/k+j3ouQpXycZ8TJ5o3QEa72pM6gkSrp+NtyPyXM=
    - NODE_ENV=travis
addons:
  sauce_connect: true
